# pull official base image
FROM python:3.8.3-slim-buster

# set work directory
WORKDIR /usr/src/app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Upgrade packages and install postgres drivers/dependencies
RUN apt-get update \
  && apt-get -y upgrade \
  && apt-get install -y \
  libpq-dev \
  gcc \
  python3-dev \
  musl-dev \
  netcat \
  && apt-get clean

# Upgrade pip
RUN pip install --upgrade pip

# Copy requirements, entrypoint and project
COPY ./requirements.txt ./

# Install python dependencies
RUN pip install -r requirements.txt

# Copy project
COPY app/ ./

# run entrypoint.sh
ENTRYPOINT ["/usr/src/app/entrypoint.dev.sh"]